// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: academic_navigator.proto

package server

import (
	"context"

	"coderhub/rpc/TechSphere/AcademicNavigator/academic_navigator"
	"coderhub/rpc/TechSphere/AcademicNavigator/internal/logic"
	"coderhub/rpc/TechSphere/AcademicNavigator/internal/svc"
)

type AcademicNavigatorServiceServer struct {
	svcCtx *svc.ServiceContext
	academic_navigator.UnimplementedAcademicNavigatorServiceServer
}

func NewAcademicNavigatorServiceServer(svcCtx *svc.ServiceContext) *AcademicNavigatorServiceServer {
	return &AcademicNavigatorServiceServer{
		svcCtx: svcCtx,
	}
}

// 新增学术导航
func (s *AcademicNavigatorServiceServer) AddAcademicNavigator(ctx context.Context, in *academic_navigator.AddAcademicNavigatorRequest) (*academic_navigator.Response, error) {
	l := logic.NewAddAcademicNavigatorLogic(ctx, s.svcCtx)
	return l.AddAcademicNavigator(in)
}

// 获取学术导航
func (s *AcademicNavigatorServiceServer) GetAcademicNavigator(ctx context.Context, in *academic_navigator.GetAcademicNavigatorRequest) (*academic_navigator.GetAcademicNavigatorResponse, error) {
	l := logic.NewGetAcademicNavigatorLogic(ctx, s.svcCtx)
	return l.GetAcademicNavigator(in)
}

// 删除学术导航
func (s *AcademicNavigatorServiceServer) DeleteAcademicNavigator(ctx context.Context, in *academic_navigator.DeleteAcademicNavigatorRequest) (*academic_navigator.Response, error) {
	l := logic.NewDeleteAcademicNavigatorLogic(ctx, s.svcCtx)
	return l.DeleteAcademicNavigator(in)
}

// 点赞学术导航
func (s *AcademicNavigatorServiceServer) LikeAcademicNavigator(ctx context.Context, in *academic_navigator.LikeAcademicNavigatorRequest) (*academic_navigator.Response, error) {
	l := logic.NewLikeAcademicNavigatorLogic(ctx, s.svcCtx)
	return l.LikeAcademicNavigator(in)
}

// 取消点赞学术导航
func (s *AcademicNavigatorServiceServer) CancelLikeAcademicNavigator(ctx context.Context, in *academic_navigator.CancelLikeAcademicNavigatorRequest) (*academic_navigator.Response, error) {
	l := logic.NewCancelLikeAcademicNavigatorLogic(ctx, s.svcCtx)
	return l.CancelLikeAcademicNavigator(in)
}
