// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"coderhub/api/TechSphere/AcademicNavigator/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取学术导航
				Method:  http.MethodGet,
				Path:    "/get",
				Handler: GetAcademicNavigatorHandler(serverCtx),
			},
			{
				// 健康检查
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/academic_navigator"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 新增学术导航
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: AddAcademicNavigatorHandler(serverCtx),
			},
			{
				// 删除学术导航
				Method:  http.MethodDelete,
				Path:    "/delete/:id",
				Handler: DeleteAcademicNavigatorHandler(serverCtx),
			},
			{
				// 更新学术导航点赞数
				Method:  http.MethodPut,
				Path:    "/like_count/:id",
				Handler: UpdateAcademicNavigatorLikeCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/academic_navigator"),
	)
}
