// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package server

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"
	"coderhub/rpc/coderhub/internal/logic/imageservice"
	"coderhub/rpc/coderhub/internal/svc"
)

type ImageServiceServer struct {
	svcCtx *svc.ServiceContext
	coderhub.UnimplementedImageServiceServer
}

func NewImageServiceServer(svcCtx *svc.ServiceContext) *ImageServiceServer {
	return &ImageServiceServer{
		svcCtx: svcCtx,
	}
}

// 上传图片
func (s *ImageServiceServer) Upload(ctx context.Context, in *coderhub.UploadRequest) (*coderhub.ImageInfo, error) {
	l := imageservicelogic.NewUploadLogic(ctx, s.svcCtx)
	return l.Upload(in)
}

// 删除图片
func (s *ImageServiceServer) Delete(ctx context.Context, in *coderhub.DeleteRequest) (*coderhub.DeleteResponse, error) {
	l := imageservicelogic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

// 获取图片信息
func (s *ImageServiceServer) Get(ctx context.Context, in *coderhub.GetRequest) (*coderhub.ImageInfo, error) {
	l := imageservicelogic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

// 批量获取图片信息
func (s *ImageServiceServer) BatchGet(ctx context.Context, in *coderhub.BatchGetRequest) (*coderhub.BatchGetResponse, error) {
	l := imageservicelogic.NewBatchGetLogic(ctx, s.svcCtx)
	return l.BatchGet(in)
}

// 获取用户图片列表
func (s *ImageServiceServer) ListByUser(ctx context.Context, in *coderhub.ListByUserRequest) (*coderhub.ListByUserResponse, error) {
	l := imageservicelogic.NewListByUserLogic(ctx, s.svcCtx)
	return l.ListByUser(in)
}
