// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package server

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"
	"coderhub/rpc/coderhub/internal/logic/creatordashboardservice"
	"coderhub/rpc/coderhub/internal/svc"
)

type CreatorDashBoardServiceServer struct {
	svcCtx *svc.ServiceContext
	coderhub.UnimplementedCreatorDashBoardServiceServer
}

func NewCreatorDashBoardServiceServer(svcCtx *svc.ServiceContext) *CreatorDashBoardServiceServer {
	return &CreatorDashBoardServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CreatorDashBoardServiceServer) GetCreatorDashBoard(ctx context.Context, in *coderhub.GetCreatorDashBoardRequest) (*coderhub.GetCreatorDashBoardResponse, error) {
	l := creatordashboardservicelogic.NewGetCreatorDashBoardLogic(ctx, s.svcCtx)
	return l.GetCreatorDashBoard(in)
}
