// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AuthenticateUserRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthenticateUserResponse struct {
	Response
	Data string `json:"data"`
}

type ChangePasswordRequest struct {
	UserId      int64  `json:"user_id"`
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type ChangePasswordResponse struct {
	Response
	Data bool `json:"data"`
}

type CreateUserRequest struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserResponse struct {
	Response
	Data int64 `json:"data"`
}

type DeleteUserRequest struct {
	UserId int64 `json:"user_id"`
}

type DeleteUserResponse struct {
	Response
	Data bool `json:"data"`
}

type GetUserInfoRequest struct {
	UserId int64 `json:"user_id"`
}

type GetUserInfoResponse struct {
	Response
	Data UserInfo `json:"data"`
}

type ResetPasswordRequest struct {
	Email       string `json:"email"`
	NewPassword string `json:"new_password"`
}

type ResetPasswordResponse struct {
	Response
	Data bool `json:"data"`
}

type Response struct {
	Code    int32  `json:"code"`    // 状态码
	Message string `json:"message"` // 提示信息
}

type UpdateUserInfoRequest struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	IsAdmin  string `json:"is_admin"`
	Status   bool   `json:"status"`
}

type UpdateUserInfoResponse struct {
	Response
	Data bool `json:"data"`
}

type UserInfo struct {
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	Avatar    string `json:"avatar"`
	Email     string `json:"email"`
	Nickname  string `json:"nickname"`
	IsAdmin   string `json:"is_admin"`
	Status    bool   `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}
