// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AuthenticateUserRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthenticateUserResponse struct {
	Authenticated bool `json:"authenticated"`
}

type ChangePasswordRequest struct {
	UserId      int64  `json:"user_id"`
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type ChangePasswordResponse struct {
	Success bool `json:"success"`
}

type CheckUserExistsRequest struct {
	Username string `json:"username"`
}

type CheckUserExistsResponse struct {
	Exists bool `json:"exists"`
}

type CreateUserRequest struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserResponse struct {
	UserId int64 `json:"user_id"`
}

type DeleteUserRequest struct {
	UserId int64 `json:"user_id"`
}

type DeleteUserResponse struct {
	Success bool `json:"success"`
}

type GenerateTokenRequest struct {
	UserId int64 `json:"user_id"`
}

type GenerateTokenResponse struct {
	Token string `json:"token"`
}

type GetUserInfoRequest struct {
	UserId int64 `json:"user_id"`
}

type GetUserInfoResponse struct {
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	Avatar    string `json:"avatar"`
	Email     string `json:"email"`
	Nickname  string `json:"nickname"`
	IsAdmin   string `json:"is_admin"`
	Status    bool   `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type ResetPasswordRequest struct {
	Email       string `json:"email"`
	NewPassword string `json:"new_password"`
}

type ResetPasswordResponse struct {
	Success bool `json:"success"`
}

type UpdateUserInfoRequest struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	IsAdmin  string `json:"is_admin"`
	Status   bool   `json:"status"`
}

type UpdateUserInfoResponse struct {
	Success bool `json:"success"`
}
