// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"coderhub/api/TechSphere/Comment/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取评论列表
				Method:  http.MethodGet,
				Path:    "/articles/:article_id/comments",
				Handler: GetCommentsHandler(serverCtx),
			},
			{
				// 创建评论
				Method:  http.MethodPost,
				Path:    "/comments",
				Handler: CreateCommentHandler(serverCtx),
			},
			{
				// 获取单个评论
				Method:  http.MethodGet,
				Path:    "/comments/:comment_id",
				Handler: GetCommentHandler(serverCtx),
			},
			{
				// 删除评论
				Method:  http.MethodDelete,
				Path:    "/comments/:comment_id",
				Handler: DeleteCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
