// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package questionbankcategoryservice

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcademicNavigator                   = coderhub.AcademicNavigator
	AddAcademicNavigatorRequest         = coderhub.AddAcademicNavigatorRequest
	Article                             = coderhub.Article
	ArticleAdditionalInfo               = coderhub.ArticleAdditionalInfo
	ArticleTag                          = coderhub.ArticleTag
	AuthorizeRequest                    = coderhub.AuthorizeRequest
	AuthorizeResponse                   = coderhub.AuthorizeResponse
	BatchCreateRelationRequest          = coderhub.BatchCreateRelationRequest
	BatchCreateRelationResponse         = coderhub.BatchCreateRelationResponse
	BatchDeleteRelationRequest          = coderhub.BatchDeleteRelationRequest
	BatchDeleteRelationResponse         = coderhub.BatchDeleteRelationResponse
	BatchGetImagesByEntityRequest       = coderhub.BatchGetImagesByEntityRequest
	BatchGetImagesByEntityResponse      = coderhub.BatchGetImagesByEntityResponse
	BatchGetRequest                     = coderhub.BatchGetRequest
	BatchGetResponse                    = coderhub.BatchGetResponse
	BatchGetUserByIDRequest             = coderhub.BatchGetUserByIDRequest
	BatchGetUserByIDResponse            = coderhub.BatchGetUserByIDResponse
	CancelLikeAcademicNavigatorRequest  = coderhub.CancelLikeAcademicNavigatorRequest
	ChangePasswordRequest               = coderhub.ChangePasswordRequest
	ChangePasswordResponse              = coderhub.ChangePasswordResponse
	CheckUserExistsRequest              = coderhub.CheckUserExistsRequest
	CheckUserExistsResponse             = coderhub.CheckUserExistsResponse
	Comment                             = coderhub.Comment
	CreateArticleRequest                = coderhub.CreateArticleRequest
	CreateArticleResponse               = coderhub.CreateArticleResponse
	CreateArticleTagRequest             = coderhub.CreateArticleTagRequest
	CreateArticleTagResponse            = coderhub.CreateArticleTagResponse
	CreateCommentRequest                = coderhub.CreateCommentRequest
	CreateCommentResponse               = coderhub.CreateCommentResponse
	CreateEmotionRequest                = coderhub.CreateEmotionRequest
	CreateEmotionResponse               = coderhub.CreateEmotionResponse
	CreateFavorFoldRequest              = coderhub.CreateFavorFoldRequest
	CreateFavorFoldResponse             = coderhub.CreateFavorFoldResponse
	CreateFavorRequest                  = coderhub.CreateFavorRequest
	CreateFavorResponse                 = coderhub.CreateFavorResponse
	CreateQuestionBankCategoryRequest   = coderhub.CreateQuestionBankCategoryRequest
	CreateQuestionBankCategoryResponse  = coderhub.CreateQuestionBankCategoryResponse
	CreateQuestionBankRequest           = coderhub.CreateQuestionBankRequest
	CreateQuestionBankResponse          = coderhub.CreateQuestionBankResponse
	CreateQuestionRequest               = coderhub.CreateQuestionRequest
	CreateQuestionResponse              = coderhub.CreateQuestionResponse
	CreateRelationRequest               = coderhub.CreateRelationRequest
	CreateRelationResponse              = coderhub.CreateRelationResponse
	CreateUserFollowReq                 = coderhub.CreateUserFollowReq
	CreateUserFollowResp                = coderhub.CreateUserFollowResp
	CreateUserRequest                   = coderhub.CreateUserRequest
	CreateUserResponse                  = coderhub.CreateUserResponse
	DeleteAcademicNavigatorRequest      = coderhub.DeleteAcademicNavigatorRequest
	DeleteArticleRequest                = coderhub.DeleteArticleRequest
	DeleteArticleResponse               = coderhub.DeleteArticleResponse
	DeleteArticleTagRequest             = coderhub.DeleteArticleTagRequest
	DeleteArticleTagResponse            = coderhub.DeleteArticleTagResponse
	DeleteByEntityIDRequest             = coderhub.DeleteByEntityIDRequest
	DeleteByEntityIDResponse            = coderhub.DeleteByEntityIDResponse
	DeleteCommentRequest                = coderhub.DeleteCommentRequest
	DeleteCommentResponse               = coderhub.DeleteCommentResponse
	DeleteEmotionRequest                = coderhub.DeleteEmotionRequest
	DeleteEmotionResponse               = coderhub.DeleteEmotionResponse
	DeleteFavorFoldRequest              = coderhub.DeleteFavorFoldRequest
	DeleteFavorFoldResponse             = coderhub.DeleteFavorFoldResponse
	DeleteFavorRequest                  = coderhub.DeleteFavorRequest
	DeleteFavorResponse                 = coderhub.DeleteFavorResponse
	DeleteQuestionBankCategoryRequest   = coderhub.DeleteQuestionBankCategoryRequest
	DeleteQuestionBankCategoryResponse  = coderhub.DeleteQuestionBankCategoryResponse
	DeleteQuestionBankRequest           = coderhub.DeleteQuestionBankRequest
	DeleteQuestionBankResponse          = coderhub.DeleteQuestionBankResponse
	DeleteQuestionRequest               = coderhub.DeleteQuestionRequest
	DeleteQuestionResponse              = coderhub.DeleteQuestionResponse
	DeleteRequest                       = coderhub.DeleteRequest
	DeleteResponse                      = coderhub.DeleteResponse
	DeleteUserFollowReq                 = coderhub.DeleteUserFollowReq
	DeleteUserFollowResp                = coderhub.DeleteUserFollowResp
	DeleteUserRequest                   = coderhub.DeleteUserRequest
	DeleteUserResponse                  = coderhub.DeleteUserResponse
	Emotion                             = coderhub.Emotion
	EntityInfo                          = coderhub.EntityInfo
	Favor                               = coderhub.Favor
	FavorFold                           = coderhub.FavorFold
	FavorPreview                        = coderhub.FavorPreview
	GenerateTokenRequest                = coderhub.GenerateTokenRequest
	GenerateTokenResponse               = coderhub.GenerateTokenResponse
	GetAcademicNavigatorRequest         = coderhub.GetAcademicNavigatorRequest
	GetAcademicNavigatorResponse        = coderhub.GetAcademicNavigatorResponse
	GetArticleRequest                   = coderhub.GetArticleRequest
	GetArticleResponse                  = coderhub.GetArticleResponse
	GetArticleTagListRequest            = coderhub.GetArticleTagListRequest
	GetArticleTagListResponse           = coderhub.GetArticleTagListResponse
	GetArticlesRequest                  = coderhub.GetArticlesRequest
	GetArticlesResponse                 = coderhub.GetArticlesResponse
	GetCommentRepliesRequest            = coderhub.GetCommentRepliesRequest
	GetCommentRepliesResponse           = coderhub.GetCommentRepliesResponse
	GetCommentRequest                   = coderhub.GetCommentRequest
	GetCommentResponse                  = coderhub.GetCommentResponse
	GetCommentsRequest                  = coderhub.GetCommentsRequest
	GetCommentsResponse                 = coderhub.GetCommentsResponse
	GetEmotionListRequest               = coderhub.GetEmotionListRequest
	GetEmotionListResponse              = coderhub.GetEmotionListResponse
	GetEntitiesByImageRequest           = coderhub.GetEntitiesByImageRequest
	GetEntitiesByImageResponse          = coderhub.GetEntitiesByImageResponse
	GetFavorFoldListRequest             = coderhub.GetFavorFoldListRequest
	GetFavorFoldListResponse            = coderhub.GetFavorFoldListResponse
	GetFavorListRequest                 = coderhub.GetFavorListRequest
	GetFavorListResponse                = coderhub.GetFavorListResponse
	GetImagesByEntityRequest            = coderhub.GetImagesByEntityRequest
	GetImagesByEntityResponse           = coderhub.GetImagesByEntityResponse
	GetMutualFollowsReq                 = coderhub.GetMutualFollowsReq
	GetMutualFollowsResp                = coderhub.GetMutualFollowsResp
	GetQuestionBankCategoryListRequest  = coderhub.GetQuestionBankCategoryListRequest
	GetQuestionBankCategoryListResponse = coderhub.GetQuestionBankCategoryListResponse
	GetQuestionBankListRequest          = coderhub.GetQuestionBankListRequest
	GetQuestionBankListResponse         = coderhub.GetQuestionBankListResponse
	GetQuestionRequest                  = coderhub.GetQuestionRequest
	GetQuestionResponse                 = coderhub.GetQuestionResponse
	GetQuestionTreeRequest              = coderhub.GetQuestionTreeRequest
	GetQuestionTreeResponse             = coderhub.GetQuestionTreeResponse
	GetRequest                          = coderhub.GetRequest
	GetSystemProviderTagListRequest     = coderhub.GetSystemProviderTagListRequest
	GetSystemProviderTagListResponse    = coderhub.GetSystemProviderTagListResponse
	GetUserFansReq                      = coderhub.GetUserFansReq
	GetUserFansResp                     = coderhub.GetUserFansResp
	GetUserFollowsReq                   = coderhub.GetUserFollowsReq
	GetUserFollowsResp                  = coderhub.GetUserFollowsResp
	GetUserInfoByUsernameRequest        = coderhub.GetUserInfoByUsernameRequest
	GetUserInfoRequest                  = coderhub.GetUserInfoRequest
	Image                               = coderhub.Image
	ImageInfo                           = coderhub.ImageInfo
	ImageRelation                       = coderhub.ImageRelation
	IsUserFollowedReq                   = coderhub.IsUserFollowedReq
	IsUserFollowedResp                  = coderhub.IsUserFollowedResp
	LikeAcademicNavigatorRequest        = coderhub.LikeAcademicNavigatorRequest
	ListByUserRequest                   = coderhub.ListByUserRequest
	ListByUserResponse                  = coderhub.ListByUserResponse
	ListRecommendedArticlesRequest      = coderhub.ListRecommendedArticlesRequest
	ListRecommendedArticlesResponse     = coderhub.ListRecommendedArticlesResponse
	QuestionBank                        = coderhub.QuestionBank
	QuestionBankCategory                = coderhub.QuestionBankCategory
	QuestionTreeNode                    = coderhub.QuestionTreeNode
	ResetPasswordByLinkRequest          = coderhub.ResetPasswordByLinkRequest
	ResetPasswordByLinkResponse         = coderhub.ResetPasswordByLinkResponse
	ResetPasswordRequest                = coderhub.ResetPasswordRequest
	ResetPasswordResponse               = coderhub.ResetPasswordResponse
	Response                            = coderhub.Response
	UpdateArticleRequest                = coderhub.UpdateArticleRequest
	UpdateArticleResponse               = coderhub.UpdateArticleResponse
	UpdateArticleTagUsageCountRequest   = coderhub.UpdateArticleTagUsageCountRequest
	UpdateArticleTagUsageCountResponse  = coderhub.UpdateArticleTagUsageCountResponse
	UpdateCommentLikeCountRequest       = coderhub.UpdateCommentLikeCountRequest
	UpdateCommentLikeCountResponse      = coderhub.UpdateCommentLikeCountResponse
	UpdateFavorFoldRequest              = coderhub.UpdateFavorFoldRequest
	UpdateFavorFoldResponse             = coderhub.UpdateFavorFoldResponse
	UpdateLikeCountRequest              = coderhub.UpdateLikeCountRequest
	UpdateLikeCountResponse             = coderhub.UpdateLikeCountResponse
	UpdateUserInfoRequest               = coderhub.UpdateUserInfoRequest
	UpdateUserInfoResponse              = coderhub.UpdateUserInfoResponse
	UploadAvatarRequest                 = coderhub.UploadAvatarRequest
	UploadAvatarResponse                = coderhub.UploadAvatarResponse
	UploadImageInfo                     = coderhub.UploadImageInfo
	UploadRequest                       = coderhub.UploadRequest
	UserFollowInfo                      = coderhub.UserFollowInfo
	UserInfo                            = coderhub.UserInfo

	QuestionBankCategoryService interface {
		CreateQuestionBankCategory(ctx context.Context, in *CreateQuestionBankCategoryRequest, opts ...grpc.CallOption) (*CreateQuestionBankCategoryResponse, error)
		DeleteQuestionBankCategory(ctx context.Context, in *DeleteQuestionBankCategoryRequest, opts ...grpc.CallOption) (*DeleteQuestionBankCategoryResponse, error)
		GetQuestionBankCategoryList(ctx context.Context, in *GetQuestionBankCategoryListRequest, opts ...grpc.CallOption) (*GetQuestionBankCategoryListResponse, error)
	}

	defaultQuestionBankCategoryService struct {
		cli zrpc.Client
	}
)

func NewQuestionBankCategoryService(cli zrpc.Client) QuestionBankCategoryService {
	return &defaultQuestionBankCategoryService{
		cli: cli,
	}
}

func (m *defaultQuestionBankCategoryService) CreateQuestionBankCategory(ctx context.Context, in *CreateQuestionBankCategoryRequest, opts ...grpc.CallOption) (*CreateQuestionBankCategoryResponse, error) {
	client := coderhub.NewQuestionBankCategoryServiceClient(m.cli.Conn())
	return client.CreateQuestionBankCategory(ctx, in, opts...)
}

func (m *defaultQuestionBankCategoryService) DeleteQuestionBankCategory(ctx context.Context, in *DeleteQuestionBankCategoryRequest, opts ...grpc.CallOption) (*DeleteQuestionBankCategoryResponse, error) {
	client := coderhub.NewQuestionBankCategoryServiceClient(m.cli.Conn())
	return client.DeleteQuestionBankCategory(ctx, in, opts...)
}

func (m *defaultQuestionBankCategoryService) GetQuestionBankCategoryList(ctx context.Context, in *GetQuestionBankCategoryListRequest, opts ...grpc.CallOption) (*GetQuestionBankCategoryListResponse, error) {
	client := coderhub.NewQuestionBankCategoryServiceClient(m.cli.Conn())
	return client.GetQuestionBankCategoryList(ctx, in, opts...)
}
