server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp
  flatMessage: true
  zookeeperHosts:
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    canal.tcp.server.host: canal:11111
    canal.tcp.zookeeper.hosts:
    canal.tcp.batch.size: 500
    canal.tcp.username:
    canal.tcp.password:

  srcDataSources:
    defaultDS:
      url: jdbc:mysql://mysql:3306/coderhub?useUnicode=true
      username: canal
      password: canal
  canalAdapters:
    - instance: example
      groups:
      - groupId: g1
        outerAdapters:
          - name: es7
            key: articles
            hosts: elasticsearch:9200
            properties:
              mode: rest
              security.auth: elastic:2214380963Wx!!
              cluster.name: es-docker-cluster 