openapi: 3.0.0
info:
  title: 评论服务 API
  description: 提供评论相关的 HTTP API 接口
  version: 1.0.0
  contact:
    name: Xi-Yuer

components:
  securitySchemes:
    Auth:
      type: apiKey
      name: Authorization
      in: header
  
  schemas:
    Response:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: 状态码
        message:
          type: string
          description: 提示信息
    
    CommentImage:
      type: object
      properties:
        image_id:
          type: string
          description: 图片ID
        url:
          type: string
          description: 图片URL
        thumbnail_url:
          type: string
          description: 缩略图URL
    
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 评论ID
        article_id:
          type: integer
          format: int64
          description: 文章ID
        content:
          type: string
          description: 评论内容
        parent_id:
          type: integer
          format: int64
          description: 父评论ID
        user_id:
          type: integer
          format: int64
          description: 评论者ID
        created_at:
          type: integer
          format: int64
          description: 创建时间
        updated_at:
          type: integer
          format: int64
          description: 更新时间
        replies:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
          description: 子评论列表
        like_count:
          type: integer
          format: int32
          description: 点赞数
        images:
          type: array
          items:
            $ref: '#/components/schemas/CommentImage'
          description: 评论图片列表

    CreateCommentReq:
      type: object
      required:
        - article_id
        - content
      properties:
        article_id:
          type: integer
          format: int64
          description: 文章ID
        content:
          type: string
          description: 评论内容
        parent_id:
          type: integer
          format: int64
          description: 父评论ID（可选）
        reply_to_uid:
          type: integer
          format: int64
          description: 回复的目标用户ID（可选）
        image_ids:
          type: array
          items:
            type: string
          description: 图片ID列表

    CreateCommentResp:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/Comment'

    GetCommentsReq:
      type: object
      required:
        - article_id
      properties:
        article_id:
          type: integer
          format: int64
          description: 文章ID
        page:
          type: integer
          format: int32
          description: 页码
        page_size:
          type: integer
          format: int32
          description: 每页数量

    List:
      type: object
      properties:
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
          description: 评论列表
        total:
          type: integer
          format: int32
          description: 总评论数

    GetCommentsResp:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/List'

    GetCommentReq:
      type: object
      required:
        - comment_id
      properties:
        comment_id:
          type: integer
          format: int64
          description: 评论ID

    GetCommentResp:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/Comment'

    DeleteCommentReq:
      type: object
      required:
        - comment_id
      properties:
        comment_id:
          type: integer
          format: int64
          description: 评论ID

    DeleteCommentResp:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            data:
              type: boolean
              description: 删除是否成功

    HealthResp:
      allOf:
        - $ref: '#/components/schemas/Response'

paths:
  /comments/health:
    get:
      summary: 健康检查
      operationId: Health
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResp'

  /comments/create:
    post:
      summary: 创建评论
      operationId: CreateComment
      security:
        - Auth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCommentReq'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCommentResp'

  /comments/article/{article_id}:
    get:
      summary: 获取评论列表
      operationId: GetComments
      security:
        - Auth: []
      parameters:
        - name: article_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: 文章ID
        - name: page
          in: query
          schema:
            type: integer
            format: int32
          description: 页码
        - name: page_size
          in: query
          schema:
            type: integer
            format: int32
          description: 每页数量
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCommentsResp'
  /comments/{comment_id}:
    get:
      summary: 获取单个评论
      operationId: GetComment
      security:
        - Auth: []
      parameters:
        - name: comment_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: 评论ID
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCommentResp'
    delete:
      summary: 删除评论
      operationId: DeleteComment
      security:
        - Auth: []
      parameters:
        - name: comment_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: 评论ID
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteCommentResp'

  /comments/replies/{comment_id}:
    get:
      summary: 获取某条评论的子评论列表
      operationId: GetCommentReplies
      security:
        - Auth: []
      parameters:
        - name: comment_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: 评论ID
        - name: page
          in: query
          schema:
            type: integer
            format: int32
          description: 页码
        - name: page_size
          in: query
          schema:
            type: integer
            format: int32
          description: 每页数量
      responses:  
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCommentRepliesResp'