openapi: 3.0.0
info:
  title: 评论服务 API
  description: 提供评论相关的 HTTP API 接口
  version: 1.0.0
  contact:
    name: Xi-Yuer

components:
  schemas:
    Response:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: 状态码
        message:
          type: string
          description: 提示信息
    
    CommentImage:
      type: object
      properties:
        image_id:
          type: string
          description: 图片ID
        url:
          type: string
          description: 图片URL
        thumbnail_url:
          type: string
          description: 缩略图URL
    
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 评论ID
        article_id:
          type: integer
          format: int64
          description: 文章ID
        content:
          type: string
          description: 评论内容
        parent_id:
          type: integer
          format: int64
          description: 父评论ID
        user_id:
          type: integer
          format: int64
          description: 评论者ID
        created_at:
          type: integer
          format: int64
          description: 创建时间
        updated_at:
          type: integer
          format: int64
          description: 更新时间
        replies:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
          description: 子评论列表
        like_count:
          type: integer
          format: int32
          description: 点赞数
        images:
          type: array
          items:
            $ref: '#/components/schemas/CommentImage'
          description: 评论图片列表

paths:
  /comments/health:
    get:
      summary: 健康检查
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

  /comments/create:
    post:
      summary: 创建评论
      security:
        - Auth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                article_id:
                  type: integer
                  format: int64
                  description: 文章ID
                content:
                  type: string
                  description: 评论内容
                parent_id:
                  type: integer
                  format: int64
                  description: 父评论ID（可选）
                image_ids:
                  type: array
                  items:
                    type: string
                  description: 图片ID列表
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Comment'

  /comments/article/{article_id}:
    get:
      summary: 获取评论列表
      security:
        - Auth: []
      parameters:
        - name: article_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          schema:
            type: integer
            format: int32
        - name: page_size
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          comments:
                            type: array
                            items:
                              $ref: '#/components/schemas/Comment'
                          total:
                            type: integer
                            format: int32

  /comments/{comment_id}:
    get:
      summary: 获取单个评论
      security:
        - Auth: []
      parameters:
        - name: comment_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Comment'
    
    delete:
      summary: 删除评论
      security:
        - Auth: []
      parameters:
        - name: comment_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Response'
                  - type: object
                    properties:
                      data:
                        type: boolean