// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package server

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"
	"coderhub/rpc/coderhub/internal/logic/sandpackprojectsservice"
	"coderhub/rpc/coderhub/internal/svc"
)

type SandpackProjectsServiceServer struct {
	svcCtx *svc.ServiceContext
	coderhub.UnimplementedSandpackProjectsServiceServer
}

func NewSandpackProjectsServiceServer(svcCtx *svc.ServiceContext) *SandpackProjectsServiceServer {
	return &SandpackProjectsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SandpackProjectsServiceServer) CreateSandpackProjects(ctx context.Context, in *coderhub.CreateSandpackProjectsRequest) (*coderhub.CreateSandpackProjectsResponse, error) {
	l := sandpackprojectsservicelogic.NewCreateSandpackProjectsLogic(ctx, s.svcCtx)
	return l.CreateSandpackProjects(in)
}

func (s *SandpackProjectsServiceServer) GetSandpackProjects(ctx context.Context, in *coderhub.GetSandpackProjectsRequest) (*coderhub.SandpackProjects, error) {
	l := sandpackprojectsservicelogic.NewGetSandpackProjectsLogic(ctx, s.svcCtx)
	return l.GetSandpackProjects(in)
}
