// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package server

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"
	"coderhub/rpc/coderhub/internal/logic/signinservice"
	"coderhub/rpc/coderhub/internal/svc"
)

type SignInServiceServer struct {
	svcCtx *svc.ServiceContext
	coderhub.UnimplementedSignInServiceServer
}

func NewSignInServiceServer(svcCtx *svc.ServiceContext) *SignInServiceServer {
	return &SignInServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SignInServiceServer) UserSignIn(ctx context.Context, in *coderhub.UserSignInRequest) (*coderhub.SignInResponse, error) {
	l := signinservicelogic.NewUserSignInLogic(ctx, s.svcCtx)
	return l.UserSignIn(in)
}

func (s *SignInServiceServer) GetUserSignInMonth(ctx context.Context, in *coderhub.GetUserSignInMonthRequest) (*coderhub.SignInResponse, error) {
	l := signinservicelogic.NewGetUserSignInMonthLogic(ctx, s.svcCtx)
	return l.GetUserSignInMonth(in)
}
