// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package server

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"
	"coderhub/rpc/coderhub/internal/logic/messageservice"
	"coderhub/rpc/coderhub/internal/svc"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	coderhub.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServiceServer) CreateMessage(ctx context.Context, in *coderhub.CreateMessageRequest) (*coderhub.CreateMessageResponse, error) {
	l := messageservicelogic.NewCreateMessageLogic(ctx, s.svcCtx)
	return l.CreateMessage(in)
}

func (s *MessageServiceServer) DeleteMessage(ctx context.Context, in *coderhub.DeleteMessageRequest) (*coderhub.DeleteMessageResponse, error) {
	l := messageservicelogic.NewDeleteMessageLogic(ctx, s.svcCtx)
	return l.DeleteMessage(in)
}

func (s *MessageServiceServer) GetMessageList(ctx context.Context, in *coderhub.GetMessageListRequest) (*coderhub.GetMessageListResponse, error) {
	l := messageservicelogic.NewGetMessageListLogic(ctx, s.svcCtx)
	return l.GetMessageList(in)
}
