// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"coderhub/api/UserFollow/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户粉丝列表
				Method:  http.MethodGet,
				Path:    "/get_user_fans",
				Handler: GetUserFansHandler(serverCtx),
			},
			{
				// 获取用户关注列表
				Method:  http.MethodGet,
				Path:    "/get_user_follows",
				Handler: GetUserFollowsHandler(serverCtx),
			},
			{
				// 健康检查
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user_follow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建关注关系
				Method:  http.MethodPost,
				Path:    "/create_user_follow",
				Handler: CreateUserFollowHandler(serverCtx),
			},
			{
				// 取消关注
				Method:  http.MethodPost,
				Path:    "/delete_user_follow",
				Handler: DeleteUserFollowHandler(serverCtx),
			},
			{
				// 获取互相关注列表
				Method:  http.MethodGet,
				Path:    "/get_mutual_follows",
				Handler: GetMutualFollowsHandler(serverCtx),
			},
			{
				// 检查是否关注
				Method:  http.MethodPost,
				Path:    "/is_user_followed",
				Handler: IsUserFollowedHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/user_follow"),
	)
}
