// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package server

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"
	"coderhub/rpc/coderhub/internal/logic/sandpackprojectfilesservice"
	"coderhub/rpc/coderhub/internal/svc"
)

type SandpackProjectFilesServiceServer struct {
	svcCtx *svc.ServiceContext
	coderhub.UnimplementedSandpackProjectFilesServiceServer
}

func NewSandpackProjectFilesServiceServer(svcCtx *svc.ServiceContext) *SandpackProjectFilesServiceServer {
	return &SandpackProjectFilesServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SandpackProjectFilesServiceServer) CreateSandpackProjectFiles(ctx context.Context, in *coderhub.SandpackProjectFilesResponse) (*coderhub.CreateSandpackProjectFilesResponse, error) {
	l := sandpackprojectfilesservicelogic.NewCreateSandpackProjectFilesLogic(ctx, s.svcCtx)
	return l.CreateSandpackProjectFiles(in)
}

func (s *SandpackProjectFilesServiceServer) GetSandpackProjectFiles(ctx context.Context, in *coderhub.GetSandpackProjectFilesRequest) (*coderhub.SandpackProjectFilesResponse, error) {
	l := sandpackprojectfilesservicelogic.NewGetSandpackProjectFilesLogic(ctx, s.svcCtx)
	return l.GetSandpackProjectFiles(in)
}
