// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package server

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"
	"coderhub/rpc/coderhub/internal/logic/schoolexpservice"
	"coderhub/rpc/coderhub/internal/svc"
)

type SchoolExpServiceServer struct {
	svcCtx *svc.ServiceContext
	coderhub.UnimplementedSchoolExpServiceServer
}

func NewSchoolExpServiceServer(svcCtx *svc.ServiceContext) *SchoolExpServiceServer {
	return &SchoolExpServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SchoolExpServiceServer) CreateSchoolExp(ctx context.Context, in *coderhub.CreateSchoolExpRequest) (*coderhub.CreateSchoolExpResponse, error) {
	l := schoolexpservicelogic.NewCreateSchoolExpLogic(ctx, s.svcCtx)
	return l.CreateSchoolExp(in)
}

func (s *SchoolExpServiceServer) DeleteSchoolExp(ctx context.Context, in *coderhub.DeleteSchoolExpRequest) (*coderhub.DeleteSchoolExpResponse, error) {
	l := schoolexpservicelogic.NewDeleteSchoolExpLogic(ctx, s.svcCtx)
	return l.DeleteSchoolExp(in)
}

func (s *SchoolExpServiceServer) GetSchoolExpList(ctx context.Context, in *coderhub.GetSchoolExpListRequest) (*coderhub.GetSchoolExpListResponse, error) {
	l := schoolexpservicelogic.NewGetSchoolExpListLogic(ctx, s.svcCtx)
	return l.GetSchoolExpList(in)
}
