// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package server

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"
	"coderhub/rpc/coderhub/internal/logic/questionbankcategoryservice"
	"coderhub/rpc/coderhub/internal/svc"
)

type QuestionBankCategoryServiceServer struct {
	svcCtx *svc.ServiceContext
	coderhub.UnimplementedQuestionBankCategoryServiceServer
}

func NewQuestionBankCategoryServiceServer(svcCtx *svc.ServiceContext) *QuestionBankCategoryServiceServer {
	return &QuestionBankCategoryServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *QuestionBankCategoryServiceServer) CreateQuestionBankCategory(ctx context.Context, in *coderhub.CreateQuestionBankCategoryRequest) (*coderhub.CreateQuestionBankCategoryResponse, error) {
	l := questionbankcategoryservicelogic.NewCreateQuestionBankCategoryLogic(ctx, s.svcCtx)
	return l.CreateQuestionBankCategory(in)
}

func (s *QuestionBankCategoryServiceServer) DeleteQuestionBankCategory(ctx context.Context, in *coderhub.DeleteQuestionBankCategoryRequest) (*coderhub.DeleteQuestionBankCategoryResponse, error) {
	l := questionbankcategoryservicelogic.NewDeleteQuestionBankCategoryLogic(ctx, s.svcCtx)
	return l.DeleteQuestionBankCategory(in)
}

func (s *QuestionBankCategoryServiceServer) GetQuestionBankCategoryList(ctx context.Context, in *coderhub.GetQuestionBankCategoryListRequest) (*coderhub.GetQuestionBankCategoryListResponse, error) {
	l := questionbankcategoryservicelogic.NewGetQuestionBankCategoryListLogic(ctx, s.svcCtx)
	return l.GetQuestionBankCategoryList(in)
}
