// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package server

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"
	"coderhub/rpc/coderhub/internal/logic/emotionservice"
	"coderhub/rpc/coderhub/internal/svc"
)

type EmotionServiceServer struct {
	svcCtx *svc.ServiceContext
	coderhub.UnimplementedEmotionServiceServer
}

func NewEmotionServiceServer(svcCtx *svc.ServiceContext) *EmotionServiceServer {
	return &EmotionServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *EmotionServiceServer) CreateEmotion(ctx context.Context, in *coderhub.CreateEmotionRequest) (*coderhub.CreateEmotionResponse, error) {
	l := emotionservicelogic.NewCreateEmotionLogic(ctx, s.svcCtx)
	return l.CreateEmotion(in)
}

func (s *EmotionServiceServer) DeleteEmotion(ctx context.Context, in *coderhub.DeleteEmotionRequest) (*coderhub.DeleteEmotionResponse, error) {
	l := emotionservicelogic.NewDeleteEmotionLogic(ctx, s.svcCtx)
	return l.DeleteEmotion(in)
}

func (s *EmotionServiceServer) GetEmotionList(ctx context.Context, in *coderhub.GetEmotionListRequest) (*coderhub.GetEmotionListResponse, error) {
	l := emotionservicelogic.NewGetEmotionListLogic(ctx, s.svcCtx)
	return l.GetEmotionList(in)
}
