// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package server

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"
	"coderhub/rpc/coderhub/internal/logic/articletagservice"
	"coderhub/rpc/coderhub/internal/svc"
)

type ArticleTagServiceServer struct {
	svcCtx *svc.ServiceContext
	coderhub.UnimplementedArticleTagServiceServer
}

func NewArticleTagServiceServer(svcCtx *svc.ServiceContext) *ArticleTagServiceServer {
	return &ArticleTagServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleTagServiceServer) CreateArticleTag(ctx context.Context, in *coderhub.CreateArticleTagRequest) (*coderhub.CreateArticleTagResponse, error) {
	l := articletagservicelogic.NewCreateArticleTagLogic(ctx, s.svcCtx)
	return l.CreateArticleTag(in)
}

func (s *ArticleTagServiceServer) DeleteArticleTag(ctx context.Context, in *coderhub.DeleteArticleTagRequest) (*coderhub.DeleteArticleTagResponse, error) {
	l := articletagservicelogic.NewDeleteArticleTagLogic(ctx, s.svcCtx)
	return l.DeleteArticleTag(in)
}

func (s *ArticleTagServiceServer) GetArticleTagList(ctx context.Context, in *coderhub.GetArticleTagListRequest) (*coderhub.GetArticleTagListResponse, error) {
	l := articletagservicelogic.NewGetArticleTagListLogic(ctx, s.svcCtx)
	return l.GetArticleTagList(in)
}

func (s *ArticleTagServiceServer) GetSystemProviderTagList(ctx context.Context, in *coderhub.GetSystemProviderTagListRequest) (*coderhub.GetSystemProviderTagListResponse, error) {
	l := articletagservicelogic.NewGetSystemProviderTagListLogic(ctx, s.svcCtx)
	return l.GetSystemProviderTagList(in)
}

func (s *ArticleTagServiceServer) UpdateArticleTagUsageCount(ctx context.Context, in *coderhub.UpdateArticleTagUsageCountRequest) (*coderhub.UpdateArticleTagUsageCountResponse, error) {
	l := articletagservicelogic.NewUpdateArticleTagUsageCountLogic(ctx, s.svcCtx)
	return l.UpdateArticleTagUsageCount(in)
}
