openapi: 3.0.0
info:
  title: 图片服务接口
  description: 提供图片上传、删除、查询等功能
  version: 1.0.0
  contact:
    name: Xi-Yuer

servers:
  - url: /image
    description: 图片服务API

components:
  schemas:
    Response:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: 状态码
        message:
          type: string
          description: 提示信息
      required:
        - code
        - message
    
    ImageInfo:
      type: object
      properties:
        image_id:
          type: integer
          format: int64
          description: 图片ID
        bucket_name:
          type: string
          description: MinIO bucket名称
        object_name:
          type: string
          description: MinIO中的对象名称
        url:
          type: string
          description: 完整的访问URL
        thumbnail_url:
          type: string
          description: 缩略图URL
        content_type:
          type: string
          description: 文件MIME类型
        size:
          type: integer
          format: int64
          description: 文件大小(bytes)
        width:
          type: integer
          format: int32
          description: 图片宽度(px)
        height:
          type: integer
          format: int32
          description: 图片高度(px)
        upload_ip:
          type: string
          description: 上传者IP
        user_id:
          type: integer
          format: int64
          description: 上传者ID
        status:
          type: string
          description: 状态
        created_at:
          type: string
          format: date-time
          description: 创建时间
      required:
        - image_id
        - bucket_name
        - object_name
        - url
        - content_type
        - size
        - user_id
        - status
        - created_at

    UploadResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/ImageInfo'

    DeleteRequest:
      type: object
      properties:
        image_id:
          type: integer
          format: int64
          description: 图片ID
        user_id:
          type: integer
          format: int64
          description: 用户ID
      required:
        - image_id
        - user_id

    DeleteResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            success:
              type: boolean
              description: 删除是否成功

    GetRequest:
      type: object
      properties:
        image_id:
          type: integer
          format: int64
          description: 图片ID
      required:
        - image_id

    GetResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/ImageInfo'

    ListByUserRequest:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
          description: 用户ID
        page:
          type: integer
          format: int32
          description: 页码
        page_size:
          type: integer
          format: int32
          description: 每页数量
      required:
        - user_id
        - page
        - page_size

    List:
      type: object
      properties:
        images:
          type: array
          items:
            $ref: '#/components/schemas/ImageInfo'
          description: 图片列表
        total:
          type: integer
          format: int64
          description: 总数量
      required:
        - images
        - total

    ListByUserResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/List'

    HealthResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/Response'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT授权token

paths:
  /image/health:
    get:
      tags:
        - 系统
      summary: 健康检查
      description: 检查服务是否正常运行
      operationId: health
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

  /image/upload:
    post:
      tags:
        - 图片管理
      summary: 上传图片
      description: 上传新的图片文件
      operationId: uploadImage
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadRequest'
      responses:
        '200':
          description: 上传成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '401':
          description: 未授权
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

  /image/delete:
    post:
      tags:
        - 图片管理
      summary: 删除图片
      description: 删除指定的图片
      operationId: deleteImage
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteRequest'
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '401':
          description: 未授权
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '403':
          description: 无权限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

  /image/get:
    get:
      tags:
        - 图片管理
      summary: 获取图片信息
      description: 获取指定图片的详细信息
      operationId: getImage
      security:
        - bearerAuth: [ ]
      parameters:
        - name: image_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: 图片ID
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '401':
          description: 未授权
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '404':
          description: 图片不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

  /image/list:
    get:
      tags:
        - 图片管理
      summary: 获取用户图片列表
      description: 分页获取指定用户的图片列表
      operationId: listUserImages
      security:
        - bearerAuth: [ ]
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: 用户ID
        - name: page
          in: query
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
          description: 页码
        - name: page_size
          in: query
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
          description: 每页数量
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListByUserResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '401':
          description: 未授权
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

tags:
  - name: 系统
    description: 系统相关接口
  - name: 图片管理
    description: 图片管理相关接口 