// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package articleservice

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcademicNavigator                   = coderhub.AcademicNavigator
	AddAcademicNavigatorRequest         = coderhub.AddAcademicNavigatorRequest
	Article                             = coderhub.Article
	ArticleAdditionalInfo               = coderhub.ArticleAdditionalInfo
	ArticleTag                          = coderhub.ArticleTag
	AuthorizeRequest                    = coderhub.AuthorizeRequest
	AuthorizeResponse                   = coderhub.AuthorizeResponse
	BatchCreateRelationRequest          = coderhub.BatchCreateRelationRequest
	BatchCreateRelationResponse         = coderhub.BatchCreateRelationResponse
	BatchDeleteRelationRequest          = coderhub.BatchDeleteRelationRequest
	BatchDeleteRelationResponse         = coderhub.BatchDeleteRelationResponse
	BatchGetImagesByEntityRequest       = coderhub.BatchGetImagesByEntityRequest
	BatchGetImagesByEntityResponse      = coderhub.BatchGetImagesByEntityResponse
	BatchGetRequest                     = coderhub.BatchGetRequest
	BatchGetResponse                    = coderhub.BatchGetResponse
	BatchGetUserByIDRequest             = coderhub.BatchGetUserByIDRequest
	BatchGetUserByIDResponse            = coderhub.BatchGetUserByIDResponse
	CancelLikeAcademicNavigatorRequest  = coderhub.CancelLikeAcademicNavigatorRequest
	ChangePasswordRequest               = coderhub.ChangePasswordRequest
	ChangePasswordResponse              = coderhub.ChangePasswordResponse
	CheckUserExistsRequest              = coderhub.CheckUserExistsRequest
	CheckUserExistsResponse             = coderhub.CheckUserExistsResponse
	Comment                             = coderhub.Comment
	CreateArticleRequest                = coderhub.CreateArticleRequest
	CreateArticleResponse               = coderhub.CreateArticleResponse
	CreateArticleTagRequest             = coderhub.CreateArticleTagRequest
	CreateArticleTagResponse            = coderhub.CreateArticleTagResponse
	CreateCommentRequest                = coderhub.CreateCommentRequest
	CreateCommentResponse               = coderhub.CreateCommentResponse
	CreateEmotionRequest                = coderhub.CreateEmotionRequest
	CreateEmotionResponse               = coderhub.CreateEmotionResponse
	CreateFavorFoldRequest              = coderhub.CreateFavorFoldRequest
	CreateFavorFoldResponse             = coderhub.CreateFavorFoldResponse
	CreateFavorRequest                  = coderhub.CreateFavorRequest
	CreateFavorResponse                 = coderhub.CreateFavorResponse
	CreateMessageRequest                = coderhub.CreateMessageRequest
	CreateMessageResponse               = coderhub.CreateMessageResponse
	CreateQuestionBankCategoryRequest   = coderhub.CreateQuestionBankCategoryRequest
	CreateQuestionBankCategoryResponse  = coderhub.CreateQuestionBankCategoryResponse
	CreateQuestionBankRequest           = coderhub.CreateQuestionBankRequest
	CreateQuestionBankResponse          = coderhub.CreateQuestionBankResponse
	CreateQuestionRequest               = coderhub.CreateQuestionRequest
	CreateQuestionResponse              = coderhub.CreateQuestionResponse
	CreateRelationRequest               = coderhub.CreateRelationRequest
	CreateRelationResponse              = coderhub.CreateRelationResponse
	CreateSchoolExpRequest              = coderhub.CreateSchoolExpRequest
	CreateSchoolExpResponse             = coderhub.CreateSchoolExpResponse
	CreateUserFollowReq                 = coderhub.CreateUserFollowReq
	CreateUserFollowResp                = coderhub.CreateUserFollowResp
	CreateUserRequest                   = coderhub.CreateUserRequest
	CreateUserResponse                  = coderhub.CreateUserResponse
	CreateWorkExpRequest                = coderhub.CreateWorkExpRequest
	CreateWorkExpResponse               = coderhub.CreateWorkExpResponse
	DeleteAcademicNavigatorRequest      = coderhub.DeleteAcademicNavigatorRequest
	DeleteArticleRequest                = coderhub.DeleteArticleRequest
	DeleteArticleResponse               = coderhub.DeleteArticleResponse
	DeleteArticleTagRequest             = coderhub.DeleteArticleTagRequest
	DeleteArticleTagResponse            = coderhub.DeleteArticleTagResponse
	DeleteByEntityIDRequest             = coderhub.DeleteByEntityIDRequest
	DeleteByEntityIDResponse            = coderhub.DeleteByEntityIDResponse
	DeleteCommentRequest                = coderhub.DeleteCommentRequest
	DeleteCommentResponse               = coderhub.DeleteCommentResponse
	DeleteEmotionRequest                = coderhub.DeleteEmotionRequest
	DeleteEmotionResponse               = coderhub.DeleteEmotionResponse
	DeleteFavorFoldRequest              = coderhub.DeleteFavorFoldRequest
	DeleteFavorFoldResponse             = coderhub.DeleteFavorFoldResponse
	DeleteFavorRequest                  = coderhub.DeleteFavorRequest
	DeleteFavorResponse                 = coderhub.DeleteFavorResponse
	DeleteMessageRequest                = coderhub.DeleteMessageRequest
	DeleteMessageResponse               = coderhub.DeleteMessageResponse
	DeleteQuestionBankCategoryRequest   = coderhub.DeleteQuestionBankCategoryRequest
	DeleteQuestionBankCategoryResponse  = coderhub.DeleteQuestionBankCategoryResponse
	DeleteQuestionBankRequest           = coderhub.DeleteQuestionBankRequest
	DeleteQuestionBankResponse          = coderhub.DeleteQuestionBankResponse
	DeleteQuestionRequest               = coderhub.DeleteQuestionRequest
	DeleteQuestionResponse              = coderhub.DeleteQuestionResponse
	DeleteRequest                       = coderhub.DeleteRequest
	DeleteResponse                      = coderhub.DeleteResponse
	DeleteSchoolExpRequest              = coderhub.DeleteSchoolExpRequest
	DeleteSchoolExpResponse             = coderhub.DeleteSchoolExpResponse
	DeleteUserFollowReq                 = coderhub.DeleteUserFollowReq
	DeleteUserFollowResp                = coderhub.DeleteUserFollowResp
	DeleteUserRequest                   = coderhub.DeleteUserRequest
	DeleteUserResponse                  = coderhub.DeleteUserResponse
	DeleteWorkExpRequest                = coderhub.DeleteWorkExpRequest
	DeleteWorkExpResponse               = coderhub.DeleteWorkExpResponse
	Emotion                             = coderhub.Emotion
	EntityInfo                          = coderhub.EntityInfo
	Favor                               = coderhub.Favor
	FavorFold                           = coderhub.FavorFold
	FavorPreview                        = coderhub.FavorPreview
	GenerateTokenRequest                = coderhub.GenerateTokenRequest
	GenerateTokenResponse               = coderhub.GenerateTokenResponse
	GetAcademicNavigatorRequest         = coderhub.GetAcademicNavigatorRequest
	GetAcademicNavigatorResponse        = coderhub.GetAcademicNavigatorResponse
	GetArticleRequest                   = coderhub.GetArticleRequest
	GetArticleResponse                  = coderhub.GetArticleResponse
	GetArticleTagListRequest            = coderhub.GetArticleTagListRequest
	GetArticleTagListResponse           = coderhub.GetArticleTagListResponse
	GetArticlesRequest                  = coderhub.GetArticlesRequest
	GetArticlesResponse                 = coderhub.GetArticlesResponse
	GetCommentRepliesRequest            = coderhub.GetCommentRepliesRequest
	GetCommentRepliesResponse           = coderhub.GetCommentRepliesResponse
	GetCommentRequest                   = coderhub.GetCommentRequest
	GetCommentResponse                  = coderhub.GetCommentResponse
	GetCommentsRequest                  = coderhub.GetCommentsRequest
	GetCommentsResponse                 = coderhub.GetCommentsResponse
	GetEmotionListRequest               = coderhub.GetEmotionListRequest
	GetEmotionListResponse              = coderhub.GetEmotionListResponse
	GetEntitiesByImageRequest           = coderhub.GetEntitiesByImageRequest
	GetEntitiesByImageResponse          = coderhub.GetEntitiesByImageResponse
	GetFavorFoldListRequest             = coderhub.GetFavorFoldListRequest
	GetFavorFoldListResponse            = coderhub.GetFavorFoldListResponse
	GetFavorListRequest                 = coderhub.GetFavorListRequest
	GetFavorListResponse                = coderhub.GetFavorListResponse
	GetImagesByEntityRequest            = coderhub.GetImagesByEntityRequest
	GetImagesByEntityResponse           = coderhub.GetImagesByEntityResponse
	GetMessageListRequest               = coderhub.GetMessageListRequest
	GetMessageListResponse              = coderhub.GetMessageListResponse
	GetMutualFollowsReq                 = coderhub.GetMutualFollowsReq
	GetMutualFollowsResp                = coderhub.GetMutualFollowsResp
	GetQuestionBankCategoryListRequest  = coderhub.GetQuestionBankCategoryListRequest
	GetQuestionBankCategoryListResponse = coderhub.GetQuestionBankCategoryListResponse
	GetQuestionBankListRequest          = coderhub.GetQuestionBankListRequest
	GetQuestionBankListResponse         = coderhub.GetQuestionBankListResponse
	GetQuestionBankRequest              = coderhub.GetQuestionBankRequest
	GetQuestionBankResponse             = coderhub.GetQuestionBankResponse
	GetQuestionRequest                  = coderhub.GetQuestionRequest
	GetQuestionResponse                 = coderhub.GetQuestionResponse
	GetQuestionTreeRequest              = coderhub.GetQuestionTreeRequest
	GetQuestionTreeResponse             = coderhub.GetQuestionTreeResponse
	GetRequest                          = coderhub.GetRequest
	GetSchoolExpListRequest             = coderhub.GetSchoolExpListRequest
	GetSchoolExpListResponse            = coderhub.GetSchoolExpListResponse
	GetSystemProviderTagListRequest     = coderhub.GetSystemProviderTagListRequest
	GetSystemProviderTagListResponse    = coderhub.GetSystemProviderTagListResponse
	GetUnReadMessageCountRequest        = coderhub.GetUnReadMessageCountRequest
	GetUnReadMessageCountResponse       = coderhub.GetUnReadMessageCountResponse
	GetUserFansReq                      = coderhub.GetUserFansReq
	GetUserFansResp                     = coderhub.GetUserFansResp
	GetUserFollowsReq                   = coderhub.GetUserFollowsReq
	GetUserFollowsResp                  = coderhub.GetUserFollowsResp
	GetUserInfoByUsernameRequest        = coderhub.GetUserInfoByUsernameRequest
	GetUserInfoRequest                  = coderhub.GetUserInfoRequest
	GetWorkExpListRequest               = coderhub.GetWorkExpListRequest
	GetWorkExpListResponse              = coderhub.GetWorkExpListResponse
	Image                               = coderhub.Image
	ImageInfo                           = coderhub.ImageInfo
	ImageRelation                       = coderhub.ImageRelation
	IsUserFollowedReq                   = coderhub.IsUserFollowedReq
	IsUserFollowedResp                  = coderhub.IsUserFollowedResp
	LikeAcademicNavigatorRequest        = coderhub.LikeAcademicNavigatorRequest
	ListByUserRequest                   = coderhub.ListByUserRequest
	ListByUserResponse                  = coderhub.ListByUserResponse
	ListRecommendedArticlesRequest      = coderhub.ListRecommendedArticlesRequest
	ListRecommendedArticlesResponse     = coderhub.ListRecommendedArticlesResponse
	MessageListItem                     = coderhub.MessageListItem
	QuestionBank                        = coderhub.QuestionBank
	QuestionBankCategory                = coderhub.QuestionBankCategory
	QuestionTreeNode                    = coderhub.QuestionTreeNode
	ResetPasswordByLinkRequest          = coderhub.ResetPasswordByLinkRequest
	ResetPasswordByLinkResponse         = coderhub.ResetPasswordByLinkResponse
	ResetPasswordRequest                = coderhub.ResetPasswordRequest
	ResetPasswordResponse               = coderhub.ResetPasswordResponse
	Response                            = coderhub.Response
	SchoolExp                           = coderhub.SchoolExp
	UpdateArticleRequest                = coderhub.UpdateArticleRequest
	UpdateArticleResponse               = coderhub.UpdateArticleResponse
	UpdateArticleTagUsageCountRequest   = coderhub.UpdateArticleTagUsageCountRequest
	UpdateArticleTagUsageCountResponse  = coderhub.UpdateArticleTagUsageCountResponse
	UpdateCommentLikeCountRequest       = coderhub.UpdateCommentLikeCountRequest
	UpdateCommentLikeCountResponse      = coderhub.UpdateCommentLikeCountResponse
	UpdateFavorFoldRequest              = coderhub.UpdateFavorFoldRequest
	UpdateFavorFoldResponse             = coderhub.UpdateFavorFoldResponse
	UpdateLikeCountRequest              = coderhub.UpdateLikeCountRequest
	UpdateLikeCountResponse             = coderhub.UpdateLikeCountResponse
	UpdateUserInfoRequest               = coderhub.UpdateUserInfoRequest
	UpdateUserInfoResponse              = coderhub.UpdateUserInfoResponse
	UploadAvatarRequest                 = coderhub.UploadAvatarRequest
	UploadAvatarResponse                = coderhub.UploadAvatarResponse
	UploadImageInfo                     = coderhub.UploadImageInfo
	UploadRequest                       = coderhub.UploadRequest
	UserFollowInfo                      = coderhub.UserFollowInfo
	UserInfo                            = coderhub.UserInfo
	WorkExp                             = coderhub.WorkExp

	ArticleService interface {
		GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error)
		GetArticlesExtra(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*ArticleAdditionalInfo, error)
		ListRecommendedArticles(ctx context.Context, in *ListRecommendedArticlesRequest, opts ...grpc.CallOption) (*ListRecommendedArticlesResponse, error)
		ListArticles(ctx context.Context, in *GetArticlesRequest, opts ...grpc.CallOption) (*GetArticlesResponse, error)
		CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*CreateArticleResponse, error)
		UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error)
		UpdateLikeCount(ctx context.Context, in *UpdateLikeCountRequest, opts ...grpc.CallOption) (*UpdateLikeCountResponse, error)
		DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error)
	}

	defaultArticleService struct {
		cli zrpc.Client
	}
)

func NewArticleService(cli zrpc.Client) ArticleService {
	return &defaultArticleService{
		cli: cli,
	}
}

func (m *defaultArticleService) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error) {
	client := coderhub.NewArticleServiceClient(m.cli.Conn())
	return client.GetArticle(ctx, in, opts...)
}

func (m *defaultArticleService) GetArticlesExtra(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*ArticleAdditionalInfo, error) {
	client := coderhub.NewArticleServiceClient(m.cli.Conn())
	return client.GetArticlesExtra(ctx, in, opts...)
}

func (m *defaultArticleService) ListRecommendedArticles(ctx context.Context, in *ListRecommendedArticlesRequest, opts ...grpc.CallOption) (*ListRecommendedArticlesResponse, error) {
	client := coderhub.NewArticleServiceClient(m.cli.Conn())
	return client.ListRecommendedArticles(ctx, in, opts...)
}

func (m *defaultArticleService) ListArticles(ctx context.Context, in *GetArticlesRequest, opts ...grpc.CallOption) (*GetArticlesResponse, error) {
	client := coderhub.NewArticleServiceClient(m.cli.Conn())
	return client.ListArticles(ctx, in, opts...)
}

func (m *defaultArticleService) CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*CreateArticleResponse, error) {
	client := coderhub.NewArticleServiceClient(m.cli.Conn())
	return client.CreateArticle(ctx, in, opts...)
}

func (m *defaultArticleService) UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error) {
	client := coderhub.NewArticleServiceClient(m.cli.Conn())
	return client.UpdateArticle(ctx, in, opts...)
}

func (m *defaultArticleService) UpdateLikeCount(ctx context.Context, in *UpdateLikeCountRequest, opts ...grpc.CallOption) (*UpdateLikeCountResponse, error) {
	client := coderhub.NewArticleServiceClient(m.cli.Conn())
	return client.UpdateLikeCount(ctx, in, opts...)
}

func (m *defaultArticleService) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error) {
	client := coderhub.NewArticleServiceClient(m.cli.Conn())
	return client.DeleteArticle(ctx, in, opts...)
}
