// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: coderhub.proto

package server

import (
	"context"

	"coderhub/rpc/coderhub/coderhub"
	"coderhub/rpc/coderhub/internal/logic/workexpservice"
	"coderhub/rpc/coderhub/internal/svc"
)

type WorkExpServiceServer struct {
	svcCtx *svc.ServiceContext
	coderhub.UnimplementedWorkExpServiceServer
}

func NewWorkExpServiceServer(svcCtx *svc.ServiceContext) *WorkExpServiceServer {
	return &WorkExpServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *WorkExpServiceServer) CreateWorkExp(ctx context.Context, in *coderhub.CreateWorkExpRequest) (*coderhub.CreateWorkExpResponse, error) {
	l := workexpservicelogic.NewCreateWorkExpLogic(ctx, s.svcCtx)
	return l.CreateWorkExp(in)
}

func (s *WorkExpServiceServer) DeleteWorkExp(ctx context.Context, in *coderhub.DeleteWorkExpRequest) (*coderhub.DeleteWorkExpResponse, error) {
	l := workexpservicelogic.NewDeleteWorkExpLogic(ctx, s.svcCtx)
	return l.DeleteWorkExp(in)
}

func (s *WorkExpServiceServer) GetWorkExpList(ctx context.Context, in *coderhub.GetWorkExpListRequest) (*coderhub.GetWorkExpListResponse, error) {
	l := workexpservicelogic.NewGetWorkExpListLogic(ctx, s.svcCtx)
	return l.GetWorkExpList(in)
}
